Set-Location "C:\Users\venka\SAPTEST\MCSTAP1"
$env:POSTGRES_HOST = "127.0.0.1"
$env:POSTGRES_PORT = "5432"
$env:POSTGRES_DB = "mcstap"
$env:POSTGRES_USER = "mcstap"
$env:POSTGRES_PASSWORD = "mcstap_password"
Add-Content "C:\Users\venka\SAPTEST\MCSTAP1\launcher.log" "launcher started $(Get-Date -Format o)"
Add-Content "C:\Users\venka\SAPTEST\MCSTAP1\launcher.log" "cwd $(Get-Location)"
& "C:\Users\venka\SAPTEST\.venv-fastapi\Scripts\python.exe" -m uvicorn api.main:app --host 127.0.0.1 --port 8000 *> "C:\Users\venka\SAPTEST\MCSTAP1\uvicorn.combined.log"
Add-Content "C:\Users\venka\SAPTEST\MCSTAP1\launcher.log" "uvicorn exited $(Get-Date -Format o) exit=$LASTEXITCODE"
