/**
 * Ported from the legacy js/analyzer.js, js/generator.js, and js/metadata.js.
 * Field metadata table and code-generation rules are kept in lockstep with
 * the original SAP GUI recording parser so generated scripts stay consistent.
 */

export type RecordedAction = {
  seq: number;
  action: "SET_TEXT" | "SEND_VKEY" | "PRESS";
  field?: string;
  locator?: string;
  sample_value?: string;
};

export type RecordedField = {
  field: string;
  locator?: string;
  sample_value?: string;
};

export type AnalyzeResult = {
  success: boolean;
  transaction: string;
  action_count: number;
  field_count: number;
  errors: string[];
  fields: RecordedField[];
  actions: RecordedAction[];
  message?: string;
};

export type FieldMetadata = {
  variable: string;
  description: string;
  classification: string;
  generator: string;
  required: boolean;
};

const FIELD_METADATA: Record<string, FieldMetadata> = {
  "CSKSZ-KOSTL": {
    variable: "COSTCENTER",
    description: "Cost Center",
    classification: "BUSINESS_KEY",
    generator: "generate_costcenter()",
    required: true
  },
  "CSKSZ-KTEXT": {
    variable: "COSTCENTER_NAME",
    description: "Cost Center Name",
    classification: "DESCRIPTION",
    generator: "generate_name()",
    required: true
  },
  "CSKSZ-LTEXT": {
    variable: "LONG_TEXT",
    description: "Long Description",
    classification: "LONG_DESCRIPTION",
    generator: "generate_long_text()",
    required: false
  },
  "CSKSZ-VERAK": {
    variable: "RESPONSIBLE_PERSON",
    description: "Responsible Person",
    classification: "REFERENCE",
    generator: "get_valid_responsible_person()",
    required: true
  },
  "CSKSZ-PRCTR": {
    variable: "PROFIT_CENTER",
    description: "Profit Center",
    classification: "REFERENCE",
    generator: "get_valid_profit_center()",
    required: true
  }
};

export function getFieldMetadata(field: string): FieldMetadata | undefined {
  return FIELD_METADATA[field];
}

function isUsableSetTextAction(action: RecordedAction): action is RecordedAction & { field: string; locator: string } {
  if (action.action !== "SET_TEXT") return false;
  if (!action.locator) return false;
  if (action.locator === "wnd[0]/tbar[0]/okcd") return false;
  if (!action.field || action.field.trim() === "") return false;
  return Boolean(getFieldMetadata(action.field));
}

export function generateScript(analysisResults: AnalyzeResult[]): string {
  let code = "";
  code += "# ======================================\n";
  code += "# Generated By MC STAP\n";
  code += "# ======================================\n\n";

  const discoveredVariables: Record<string, FieldMetadata> = {};
  analysisResults.forEach((result) => {
    result.fields.forEach((field) => {
      const info = getFieldMetadata(field.field);
      if (info) {
        discoveredVariables[info.variable] = info;
      }
    });
  });

  code += "# Variables\n\n";
  Object.values(discoveredVariables).forEach((info) => {
    code += `# ${info.description} [${info.classification}]\n`;
    code += `${info.variable} = ${info.generator}\n\n`;
  });

  analysisResults.forEach((result) => {
    code += `\n# Transaction ${result.transaction}\n\n`;
    code += `START_TRANSACTION("${result.transaction}")\n\n`;

    result.actions.forEach((action) => {
      if (isUsableSetTextAction(action)) {
        const info = getFieldMetadata(action.field);
        if (!info) return;
        code += `session.findById("${action.locator}").text = ${info.variable}\n`;
      }
      // SEND_VKEY / PRESS are recorder noise and are intentionally not emitted.
    });

    code += "\n";
  });

  return code;
}

export type GeneratedStep = {
  parameterName: string;
  parameterValue: string;
};

export function extractGeneratedSteps(analysisResults: AnalyzeResult[]): GeneratedStep[] {
  const steps: GeneratedStep[] = [];

  analysisResults.forEach((result) => {
    result.actions.forEach((action) => {
      if (!isUsableSetTextAction(action)) return;
      const info = getFieldMetadata(action.field);
      if (!info) return;
      steps.push({ parameterName: info.variable, parameterValue: action.locator });
    });
  });

  return steps;
}
